config/routes.rb
Rails.application.routes.draw do
  # devise_for :admin_users, ActiveAdmin::Devise.config
  # ActiveAdmin.routes(self)
  devise_for :users
  resources :show_times, only: %i[new create] do
    resources :orders, only: %i[new create show]
  end
  resources :movies, only: %i[index]
  resources :customers, only: %i[index]
  get "orders", to: "orders#index"
  get "dashboard", to: "orders#dashboard"

  root "movies#index"
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: %i[ show edit update destroy ]

  # GET /movies or /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1 or /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies or /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully created." }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1 or /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully updated." }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1 or /movies/1.json
  def destroy
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url, notice: "Movie was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:name)
    end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_form.html.erb
<%= form_with(model: movie) do |form| %>
  <% if movie.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/movies/_movie.html.erb
<div id="<%= dom_id movie %>">
  <p>
    <strong>Name:</strong>
    <%= movie.name %>
  </p>

</div>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render "form", movie: @movie %>

<br>

<div>
  <%= link_to "Show this movie", @movie %> |
  <%= link_to "Back to movies", movies_path %>
</div>

app/views/movies/index.html.erb
<div>
  <div>
    <p style="color: green"><%= notice %></p>
  </div>
  <div>
    <h2 class="display-6 text-center mb-4">Movies</h2>
  </div>
  <div>
    <% @movies.each do |movie| %>
      <div class="col">
        <div class="card shadow-sm">
          <div class="card-body">
            <h4 class="card-text"><%= movie.name %></h4>
            <% if movie.show_times.active.seats_available.by_date.any? %>
              <div class="align-items-center">
                <% movie.show_times.active.seats_available.by_date.each do |show_time| %>
                  <%= link_to time_only(show_time.show_date_and_time), new_show_time_order_path(show_time.id), class: "btn btn-primary" %>
                <% end %>
              </div>
            <% else %>
              <p class="text-primary">Got Netflix? <%= movie.name %> is sold out.</p>
            <% end %>
          </div>
        </div>
      </div>
      <br>
    <% end %>
  </div>
</div>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render "form", movie: @movie %>

<br>

<div>
  <%= link_to "Back to movies", movies_path %>
</div>

app/views/movies/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @movie %>

<div>
  <%= link_to "Edit this movie", edit_movie_path(@movie) %> |
  <%= link_to "Back to movies", movies_path %>

  <%= button_to "Destroy this movie", @movie, method: :delete %>
</div>