config/routes.rb
Rails.application.routes.draw do
  # devise_for :admin_users, ActiveAdmin::Devise.config
  # ActiveAdmin.routes(self)
  devise_for :users
  resources :show_times, only: %i[new create] do
    resources :orders, only: %i[new create show]
  end
  resources :movies, only: %i[index]
  resources :customers, only: %i[index]
  get "orders", to: "orders#index"
  get "dashboard", to: "orders#dashboard"

  root "movies#index"
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders

  EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

  validates :first_name, :last_name, :credit_card_number, :expiration_date, :email, presence: true
  validates :email, format: { with: EMAIL_REGEX }
  #credit_card_number - card can have as many as 19 digits or as little as 13. Details are in README.
  validates :credit_card_number, length: { minimum: 13, maximum: 19 }, numericality: { only_integer: true }

  def full_name
    first_name + " " + last_name
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: %i[ show edit update destroy ]

  # GET /customers or /customers.json
  def index
    @q = Customer.ransack(params[:q])
    @customers = @q.result(distinct: true)
  end

  # GET /customers/1 or /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers or /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to customer_url(@customer), notice: "Customer was successfully created." }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1 or /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to customer_url(@customer), notice: "Customer was successfully updated." }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1 or /customers/1.json
  def destroy
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url, notice: "Customer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_params
      params.require(:customer).permit(:first_name, :last_name, :credit_card_number, :expiration_date, :email)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_customer.html.erb
<div id="<%= dom_id customer %>">
  <p>
    <strong>First name:</strong>
    <%= customer.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= customer.last_name %>
  </p>

  <p>
    <strong>Credit card number:</strong>
    <%= customer.credit_card_number %>
  </p>

  <p>
    <strong>Expiration date:</strong>
    <%= customer.expiration_date %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= customer.email %>
  </p>

</div>

app/views/customers/_form.html.erb
<%= form_with(model: customer) do |form| %>
  <% if customer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
        <% customer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :credit_card_number, style: "display: block" %>
    <%= form.text_field :credit_card_number %>
  </div>

  <div>
    <%= form.label :expiration_date, style: "display: block" %>
    <%= form.text_field :expiration_date %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/customers/_search_form.html.erb
<%= search_form_for @q do |f| %>
  <p>
    <%= f.label :first_name_start, style: "display: block" %>
    <%= f.search_field :first_name_start %>
  </p>
  <p>
    <%= f.label :last_name_start, style: "display: block" %>
    <%= f.search_field :last_name_start %>
  </p>
  <p>
    <%= f.label :email_cont, style: "display: block" %>
    <%= f.search_field :email_cont %>
  </p>
  <%= f.submit 'Search', class: 'btn btn-primary' %>
<% end %><br>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render "form", customer: @customer %>

<br>

<div>
  <%= link_to "Show this customer", @customer %> |
  <%= link_to "Back to customers", customers_path %>
</div>

app/views/customers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Customers</h1>

<%= render "customers/search_form" %>

<table class="table">
  <thead>
    <tr>
      <th scope="col"><%= sort_link(@q, :first_name, "First Name", default_order: :asc) %></th>
      <th scope="col"><%= sort_link(@q, :last_name, "Last Name", default_order: :asc) %></th>
      <th scope="col"><%= sort_link(@q, :email, "Email", default_order: :asc) %></th>
      <th scope="col">Number of Orders</th>
    </tr>
  </thead>
  <tbody>
      <% @customers.each do |customer| %>
        <tr>
          <td><%= customer.first_name %></td>
          <td><%= customer.last_name %></td>
          <td><%= customer.email %></td>
          <td><%= customer.orders.count %></td>
        </tr>
      <% end %>
  </tbody>
</table>

app/views/customers/new.html.erb
<h1>New customer</h1>

<%= render "form", customer: @customer %>

<br>

<div>
  <%= link_to "Back to customers", customers_path %>
</div>

app/views/customers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @customer %>

<div>
  <%= link_to "Edit this customer", edit_customer_path(@customer) %> |
  <%= link_to "Back to customers", customers_path %>

  <%= button_to "Destroy this customer", @customer, method: :delete %>
</div>