config/routes.rb
Rails.application.routes.draw do
  # devise_for :admin_users, ActiveAdmin::Devise.config
  # ActiveAdmin.routes(self)
  devise_for :users
  resources :show_times, only: %i[new create] do
    resources :orders, only: %i[new create show]
  end
  resources :movies, only: %i[index]
  resources :customers, only: %i[index]
  get "orders", to: "orders#index"
  get "dashboard", to: "orders#dashboard"

  root "movies#index"
end

app/models/show_time.rb
class ShowTime < ApplicationRecord
  belongs_to :movie
  has_many :orders
  accepts_nested_attributes_for :orders

  scope :seats_available, -> { where("sold_seats < total_seats") }
  scope :active, -> { where("show_date_and_time >= ?", Date.today) }
  scope :popular, -> { where("sold_seats > ?", 10) }
  scope :by_date, ->(sort_order = :asc) { order(show_date_and_time: sort_order) }
  scope :by_sold_seats, ->(sort_order = :desc) { order(sold_seats: sort_order) }

  def movie_name
    movie.name
  end

  def total_sale_per_show
    ticket_price * sold_seats
  end

  def available_seats
    total_seats - sold_seats
  end
end

app/controllers/show_times_controller.rb
class ShowTimesController < ApplicationController
  before_action :set_show_time, only: %i[ show edit update destroy ]

  # GET /show_times or /show_times.json
  def index
    @show_times = ShowTime.all
  end

  # GET /show_times/1 or /show_times/1.json
  def show
  end

  # GET /show_times/new
  def new
    @show_time = ShowTime.new
  end

  # GET /show_times/1/edit
  def edit
  end

  # POST /show_times or /show_times.json
  def create
    @show_time = ShowTime.new(show_time_params)

    respond_to do |format|
      if @show_time.save
        format.html { redirect_to show_time_url(@show_time), notice: "Show time was successfully created." }
        format.json { render :show, status: :created, location: @show_time }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @show_time.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /show_times/1 or /show_times/1.json
  def update
    respond_to do |format|
      if @show_time.update(show_time_params)
        format.html { redirect_to show_time_url(@show_time), notice: "Show time was successfully updated." }
        format.json { render :show, status: :ok, location: @show_time }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @show_time.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /show_times/1 or /show_times/1.json
  def destroy
    @show_time.destroy

    respond_to do |format|
      format.html { redirect_to show_times_url, notice: "Show time was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_show_time
      @show_time = ShowTime.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def show_time_params
      params.require(:show_time).permit(:total_seats, :sold_seats, :show_date_and_time, :ticket_price, :movie_id)
    end
end

app/helpers/show_times_helper.rb
module ShowTimesHelper
end

app/views/show_times/_form.html.erb
<%= form_with(model: show_time) do |form| %>
  <% if show_time.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(show_time.errors.count, "error") %> prohibited this show_time from being saved:</h2>

      <ul>
        <% show_time.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :total_seats, style: "display: block" %>
    <%= form.number_field :total_seats %>
  </div>

  <div>
    <%= form.label :sold_seats, style: "display: block" %>
    <%= form.number_field :sold_seats %>
  </div>

  <div>
    <%= form.label :show_date_and_time, style: "display: block" %>
    <%= form.datetime_field :show_date_and_time %>
  </div>

  <div>
    <%= form.label :ticket_price, style: "display: block" %>
    <%= form.number_field :ticket_price %>
  </div>

  <div>
    <%= form.label :movie_id, style: "display: block" %>
    <%= form.number_field :movie_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/show_times/_show_time.html.erb
<div id="<%= dom_id show_time %>">
  <p>
    <strong>Total seats:</strong>
    <%= show_time.total_seats %>
  </p>

  <p>
    <strong>Sold seats:</strong>
    <%= show_time.sold_seats %>
  </p>

  <p>
    <strong>Show date and time:</strong>
    <%= show_time.show_date_and_time %>
  </p>

  <p>
    <strong>Ticket price:</strong>
    <%= show_time.ticket_price %>
  </p>

  <p>
    <strong>Movie:</strong>
    <%= show_time.movie_id %>
  </p>

</div>

app/views/show_times/edit.html.erb
<h1>Editing show time</h1>

<%= render "form", show_time: @show_time %>

<br>

<div>
  <%= link_to "Show this show time", @show_time %> |
  <%= link_to "Back to show times", show_times_path %>
</div>

app/views/show_times/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Show times</h1>

<div id="show_times">
  <% @show_times.each do |show_time| %>
    <%= render show_time %>
    <p>
      <%= link_to "Show this show time", show_time %>
    </p>
  <% end %>
</div>

<%= link_to "New show time", new_show_time_path %>

app/views/show_times/new.html.erb
<h1>New show time</h1>

<%= render "form", show_time: @show_time %>

<br>

<div>
  <%= link_to "Back to show times", show_times_path %>
</div>

app/views/show_times/show.html.erb
<p style="color: green"><%= notice %></p>

<h3><%= @show_time.movie_name %></h3>
<p><%= date_and_time(@show_time.show_date_and_time) %></p>
<p>Number of seat available: <%= @show_time.total_seats %></p>
<p>Ticket price: <%= number_to_currency(@show_time.ticket_price) %></p>

<%= form_with(model: [@show_time, @show_time.orders.build], local: true) do |f| %>
  <%= f.label 'Number of Tickets' %>
  <%= f.number_field :number_of_ticket, min: 1, class: 'form-control' %>
  <%= fields_for :customer do |c| %>
    <p>
      <%= c.label :first_name %>
      <%= c.text_field :first_name, required: true %>
    </p>
    <p>
      <%= c.label :last_name %>
      <%= c.text_field :last_name, required: true %>
    </p>
    <p>
      <%= c.label :email %>
      <%= c.text_field :email, required: true %>
    </p>
      <p>
      <%= c.label :credit_card_number %>
      <%= c.text_field :credit_card_number, required: true %>
    </p>
    <p>
      <%= c.label :expiration_date %>
      <%= c.text_field :expiration_date, required: true %>
    </p>
  <% end %>
  <%= f.submit 'Submit', class: 'btn btn-primary' %>
<% end %>