config/routes.rb
Rails.application.routes.draw do
  # devise_for :admin_users, ActiveAdmin::Devise.config
  # ActiveAdmin.routes(self)
  devise_for :users
  resources :show_times, only: %i[new create] do
    resources :orders, only: %i[new create show]
  end
  resources :movies, only: %i[index]
  resources :customers, only: %i[index]
  get "orders", to: "orders#index"
  get "dashboard", to: "orders#dashboard"

  root "movies#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>LPL Cinema</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
         <%= link_to "LPL Cinema", root_path, class: "navbar-brand" %>
        <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav">
                <% if user_signed_in? %>
                  <li class="nav-item">
                    <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "Orders", orders_path, class: "nav-link" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "Customers", customers_path, class: "nav-link" %>
                  </li>
                <% end %>
            </div>
            <div class="navbar-nav ms-auto">              	
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to "Sign Out", destroy_user_session_path, class: "nav-link" %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
                </li>
              <% end %>
            </div>
        </div>
    </div>
</nav>
<div class="container">
  	<div class="p-5 my-4 bg-light rounded-3">
      <%= yield %>
    </div>
    <hr>
    <footer>
        <div class="row">
            <div class="col-md-6">
                <p>Copyright © 2022 LPL</p>
            </div>
            <div class="col-md-6 text-md-end">
                <a href="#" class="text-dark">Terms of Use</a>
                <span class="text-muted mx-2">|</span>
                <a href="#" class="text-dark">Privacy Policy</a>
            </div>
        </div>
    </footer>
</div>
</body>
</html>